feat(api): cover upload for books, read lists and collections
gotson/komga pull request #733
Opened 2021-11-23 10:15 UTC by Snd-R

Added the same functionality of custom series cover uploads to books, read lists and collections
no tests for now

2021-12-02 03:14 UTC, gotson requested changes
Thanks for the contribution!

I see one thing missing, you need to delete the thumbnails before deleting the Collection or ReadList, else the delete would fail because of foreign keys. This is already done for Books and Series, so you can take inspiration there.

2021-12-02 03:14 UTC, gotson commented on komga/src/main/kotlin/org/gotson/komga/domain/persistence/ThumbnailSeriesCollectionRepository.kt
> +  fun delete(thumbnailBookId: String)
should be `thumbnailCollection Id`

2021-12-06 03:33 UTC, gotson commented
FYI some commits on `master` have added some Flyway migrations, you will need to adjust the filenames of your migrations to be after the existing ones.

2021-12-13 08:39 UTC, gotson requested changes
`BookLifecycle.addThumbnailForBook` is called by the REST controller, but also by `LocalArtworkLifecycle`. You need to handle the marking as selected differently for local assets, you can see what has been done for series, using `MarkSelectedPreference.IF_NONE_EXIST` [here](https://github.com/gotson/komga/blob/ef399a77ba7490783281dbf4cd6ca54eb6ea642a/komga/src/main/kotlin/org/gotson/komga/domain/service/SeriesLifecycle.kt#L267-L268).

2021-12-14 14:52 UTC, Snd-R commented
With the current implementation when a new sidecar is detected it won't be marked as selected and user will have to somehow manually mark it
Should then new SIDECAR thumbnail be marked as selected when there's only one GENERATED thumbnail?

2021-12-15 14:54 UTC, gotson commented
> With the current implementation when a new sidecar is detected it won't be marked as selected and user will have to somehow manually mark it Should then new SIDECAR thumbnail be marked as selected when there's only one GENERATED thumbnail?

You mean for books? Can we reproduce that behavior in a failing test?

We could probably change "if none exist" to something like "if none or default".

2021-12-22 01:56 UTC, gotson approved these changes

2021-12-22 02:02 UTC, merged